// <auto-generated />
using System;
using FanSoft.CadTurmas.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FanSoft.CadTurmas.Data.EF.Migrations
{
    [DbContext(typeof(CadTurmasDataContext))]
    [Migration("20200103180115_MigracaoInicial")]
    partial class MigracaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FanSoft.CadTurmas.Domain.Entities.Instrutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Instrutor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlteradoEm = new DateTime(2020, 1, 3, 18, 1, 15, 21, DateTimeKind.Utc).AddTicks(9175),
                            CriadoEm = new DateTime(2020, 1, 3, 18, 1, 15, 21, DateTimeKind.Utc).AddTicks(9149),
                            Nome = "Fabiano Nalin"
                        });
                });

            modelBuilder.Entity("FanSoft.CadTurmas.Domain.Entities.Turma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataTermino")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(80)");

                    b.Property<int?>("InstrutorId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("InstrutorId");

                    b.ToTable("Turma");

                    b.HasData(
                        new
                        {
                            Id = new Guid("df9344ae-e6bb-42c5-99af-5f1543908b9c"),
                            AlteradoEm = new DateTime(2020, 1, 3, 18, 1, 15, 24, DateTimeKind.Utc).AddTicks(1561),
                            CriadoEm = new DateTime(2020, 1, 3, 18, 1, 15, 24, DateTimeKind.Utc).AddTicks(1550),
                            DataInicio = new DateTime(2020, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataTermino = new DateTime(2020, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Turma AZ 203",
                            InstrutorId = 1,
                            Nome = "AZ 203 Dez 2019"
                        });
                });

            modelBuilder.Entity("FanSoft.CadTurmas.Domain.Entities.Turma", b =>
                {
                    b.HasOne("FanSoft.CadTurmas.Domain.Entities.Instrutor", "Instrutor")
                        .WithMany("Turmas")
                        .HasForeignKey("InstrutorId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
