// <auto-generated />
using System;
using FanSoft.CadTurmas.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FanSoft.CadTurmas.Data.EF.Migrations
{
    [DbContext(typeof(CadTurmasDataContext))]
    [Migration("20200106142801_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FanSoft.CadTurmas.Domain.Entities.Instrutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Instrutor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlteradoEm = new DateTime(2020, 1, 6, 14, 28, 0, 349, DateTimeKind.Utc).AddTicks(9866),
                            CriadoEm = new DateTime(2020, 1, 6, 14, 28, 0, 349, DateTimeKind.Utc).AddTicks(9837),
                            Nome = "Fabiano Nalin"
                        });
                });

            modelBuilder.Entity("FanSoft.CadTurmas.Domain.Entities.Turma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataTermino")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(80)");

                    b.Property<int?>("InstrutorId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("InstrutorId");

                    b.ToTable("Turma");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4228a44-1a3d-46f1-b8eb-e2cfdb7ff551"),
                            AlteradoEm = new DateTime(2020, 1, 6, 14, 28, 0, 352, DateTimeKind.Utc).AddTicks(5786),
                            CriadoEm = new DateTime(2020, 1, 6, 14, 28, 0, 352, DateTimeKind.Utc).AddTicks(5776),
                            DataInicio = new DateTime(2020, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataTermino = new DateTime(2020, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Turma AZ 203",
                            InstrutorId = 1,
                            Nome = "AZ 203 Dez 2019"
                        });
                });

            modelBuilder.Entity("FanSoft.CadTurmas.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("char(32)");

                    b.Property<DateTime?>("RefreshTokenValidate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("char(88)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlteradoEm = new DateTime(2020, 1, 6, 14, 28, 0, 362, DateTimeKind.Utc).AddTicks(6163),
                            CriadoEm = new DateTime(2020, 1, 6, 14, 28, 0, 362, DateTimeKind.Utc).AddTicks(6138),
                            Email = "nalin@fansoft.com.br",
                            Nome = "Fabiano Nalin",
                            Senha = "a1n5uKDhhuf8oIt9RxEKX4dGV3ASZODELtipSBegRkM92SE+EaUhgxS0now1iRwko0nTDhfR3q7rV+Lz3btZMQ=="
                        });
                });

            modelBuilder.Entity("FanSoft.CadTurmas.Domain.Entities.Turma", b =>
                {
                    b.HasOne("FanSoft.CadTurmas.Domain.Entities.Instrutor", "Instrutor")
                        .WithMany("Turmas")
                        .HasForeignKey("InstrutorId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
