// <auto-generated />
using System;
using FanSoft.CadTurmas.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FanSoft.CadTurmas.Data.EF.Migrations
{
    [DbContext(typeof(CadTurmasDataContext))]
    partial class CadTurmasDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FanSoft.CadTurmas.Domain.Entities.Instrutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Instrutor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlteradoEm = new DateTime(2020, 1, 4, 14, 31, 50, 793, DateTimeKind.Utc).AddTicks(4525),
                            CriadoEm = new DateTime(2020, 1, 4, 14, 31, 50, 793, DateTimeKind.Utc).AddTicks(4496),
                            Nome = "Fabiano Nalin"
                        });
                });

            modelBuilder.Entity("FanSoft.CadTurmas.Domain.Entities.Turma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataTermino")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(80)");

                    b.Property<int?>("InstrutorId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("InstrutorId");

                    b.ToTable("Turma");

                    b.HasData(
                        new
                        {
                            Id = new Guid("54442804-bf96-4b64-b334-1a8ae4772326"),
                            AlteradoEm = new DateTime(2020, 1, 4, 14, 31, 50, 795, DateTimeKind.Utc).AddTicks(7950),
                            CriadoEm = new DateTime(2020, 1, 4, 14, 31, 50, 795, DateTimeKind.Utc).AddTicks(7937),
                            DataInicio = new DateTime(2020, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataTermino = new DateTime(2020, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Turma AZ 203",
                            InstrutorId = 1,
                            Nome = "AZ 203 Dez 2019"
                        });
                });

            modelBuilder.Entity("FanSoft.CadTurmas.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("char(88)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlteradoEm = new DateTime(2020, 1, 4, 14, 31, 50, 804, DateTimeKind.Utc).AddTicks(8882),
                            CriadoEm = new DateTime(2020, 1, 4, 14, 31, 50, 804, DateTimeKind.Utc).AddTicks(8864),
                            Email = "nalin@fansoft.com.br",
                            Nome = "Fabiano Nalin",
                            Senha = "a1n5uKDhhuf8oIt9RxEKX4dGV3ASZODELtipSBegRkM92SE+EaUhgxS0now1iRwko0nTDhfR3q7rV+Lz3btZMQ=="
                        });
                });

            modelBuilder.Entity("FanSoft.CadTurmas.Domain.Entities.Turma", b =>
                {
                    b.HasOne("FanSoft.CadTurmas.Domain.Entities.Instrutor", "Instrutor")
                        .WithMany("Turmas")
                        .HasForeignKey("InstrutorId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
